export const LEARNING_CONTENT_VERSION = 'first-jobber-debt-learning/1.0.0';
export const MASTERY_STATES = Object.freeze(['not_started', 'understood', 'action_taken', 'evidence_recorded']);

const bot = 'ธนาคารแห่งประเทศไทย (ธปท.)';
export const LEARNING_UNITS = Object.freeze([
  { id: 'before-overdue', duration_minutes: 3, route_tags: ['prevention'], decision: 'ถ้าคาดว่าจะจ่ายงวดหน้าไม่ไหว ให้ติดต่อเจ้าหนี้ก่อนวันครบกำหนด', question: 'ต้องรอเป็นหนี้เสียก่อนจึงขอปรับโครงสร้างหนี้ได้หรือไม่?', answer: 'ไม่ต้องรอ สามารถขอเจรจากับเจ้าหนี้ได้ก่อนเป็นหนี้เสีย', action: { id: 'record-next-due-date', label: 'บันทึกวันครบกำหนดและช่องทางติดต่อเจ้าหนี้' }, source: { url: 'https://www.bot.or.th/th/satang-story/managing-debt/debt-restructuring.html', owner: bot, reviewed_date: '2026-08-16' }, mastery_states: MASTERY_STATES },
  { id: 'ask-restructure', duration_minutes: 4, route_tags: ['direct_restructuring'], decision: 'เสนอค่างวดที่ยังเหลือเงินสำหรับค่าใช้จ่ายจำเป็น ไม่รับแผนที่ทำไม่ได้', question: 'ก่อนเซ็นแผนใหม่ควรตรวจอะไร?', answer: 'ตรวจค่างวด ดอกเบี้ย ระยะเวลา ยอดรวมที่จ่าย และวันเริ่มชำระในเอกสาร', action: { id: 'prepare-creditor-summary', label: 'เตรียมรายได้ ค่าใช้จ่ายจำเป็น และยอดที่จ่ายไหวเพื่อคุยกับเจ้าหนี้' }, source: { url: 'https://www.bot.or.th/th/satang-story/managing-debt/consumer-loan-restructuring.html', owner: bot, reviewed_date: '2026-08-16' }, mastery_states: MASTERY_STATES },
  { id: 'debt-clinic', duration_minutes: 4, route_tags: ['debt_clinic_check'], decision: 'ตรวจสิทธิ์คลินิกแก้หนี้ผ่านช่องทางทางการเมื่อเป็น NPL หนี้ไม่มีหลักประกัน', question: 'Debt Clinic ใช้กับหนี้มีหลักประกันทุกประเภทหรือไม่?', answer: 'ไม่ใช่ เส้นทางนี้ระบุบัตรเครดิต บัตรกดเงินสด และสินเชื่อส่วนบุคคลไม่มีหลักประกันตามเงื่อนไข', action: { id: 'check-debt-clinic-eligibility', label: 'รวบรวมเจ้าหนี้ ยอดหนี้ และวันค้างชำระเพื่อตรวจสิทธิ์' }, source: { url: 'https://www.bot.or.th/th/debtsolution/debtsolution-measure.html', owner: bot, reviewed_date: '2026-08-16' }, mastery_states: MASTERY_STATES },
  { id: 'clear-debt', duration_minutes: 3, route_tags: ['clear_debt_check'], decision: 'ใช้เฉพาะช่องทาง BOT/SAM เพื่อตรวจสิทธิ์ “ปิดหนี้ไว ไปต่อได้”', question: 'โครงการนี้ใช้ได้กับทุกหนี้ที่มีคำพิพากษาแล้วหรือไม่?', answer: 'ไม่ใช่ หน้าทางการระบุว่าหนี้มีคำพิพากษาแล้วไม่อยู่ในขอบเขตโครงการ', action: { id: 'verify-sam-channel', label: 'ตรวจสิทธิ์ผ่าน BOT/SAM และยืนยัน LINE ทางการก่อนทำธุรกรรม' }, source: { url: 'https://www.bot.or.th/th/cleardebt.html', owner: bot, reviewed_date: '2026-08-16' }, mastery_states: MASTERY_STATES },
  { id: 'legal-stage', duration_minutes: 5, route_tags: ['summons_mediation', 'enforcement_mediation'], decision: 'ห้ามเพิกเฉยต่อหมายศาลหรือคำพิพากษา ให้เก็บเอกสารและขอไกล่เกลี่ยผ่านหน่วยงานทางการ', question: 'การไกล่เกลี่ยชั้นบังคับคดีเป็นการบังคับให้คู่กรณียอมรับข้อเสนอหรือไม่?', answer: 'ไม่ใช่ เป็นกระบวนการสมัครใจและคู่กรณีเป็นผู้ตัดสินใจ', action: { id: 'save-case-deadline', label: 'บันทึกเลขคดี วันนัด และติดต่อกรมบังคับคดีเพื่อขอไกล่เกลี่ย' }, source: { url: 'https://www.led.go.th/news/view/19540', owner: 'กรมบังคับคดี', reviewed_date: '2026-08-16' }, mastery_states: MASTERY_STATES },
  { id: 'credit-data-dispute', duration_minutes: 3, route_tags: ['credit_data_dispute'], decision: 'ถ้าข้อมูลเครดิตผิด ให้โต้แย้งกับเจ้าหนี้และเครดิตบูโรด้วยหลักฐาน ไม่จ่ายคนกลางเพื่อล้างเครดิต', question: 'ถ้าข้อมูลเครดิตผิดควรเริ่มติดต่อใคร?', answer: 'เริ่มแจ้งสถาบันการเงินเจ้าหนี้ และยื่นขอตรวจสอบ/แก้ไขกับเครดิตบูโรได้', action: { id: 'collect-payment-evidence', label: 'รวบรวมใบเสร็จหรือหนังสือปิดบัญชีและยื่นคำร้องแก้ไข' }, source: { url: 'https://www.bot.or.th/th/satang-story/managing-debt/creditbureau.html', owner: bot, reviewed_date: '2026-08-16' }, mastery_states: MASTERY_STATES }
]);

export function unitsForRoute(route) { return LEARNING_UNITS.filter((unit) => unit.route_tags.includes(route)); }
